server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: my-secret-key
  expiration: 3600000
